CREATE TABLESPACE agro_data 
DATAFILE 'agro_data01.dbf' SIZE 200M 
AUTOEXTEND ON NEXT 50M MAXSIZE 1G;

CREATE TABLESPACE agro_idx 
DATAFILE 'agro_idx01.dbf' SIZE 100M 
AUTOEXTEND ON NEXT 25M MAXSIZE 500M;

CREATE TEMPORARY TABLESPACE agro_temp 
TEMPFILE 'agro_temp01.dbf' SIZE 50M 
AUTOEXTEND ON NEXT 10M MAXSIZE 200M;

CREATE USER agro_app_user IDENTIFIED BY agro123
DEFAULT TABLESPACE agro_data
TEMPORARY TABLESPACE agro_temp
QUOTA UNLIMITED ON agro_data
QUOTA UNLIMITED ON agro_idx;

GRANT CONNECT, RESOURCE TO agro_app_user;
GRANT CREATE VIEW, CREATE PROCEDURE, CREATE TRIGGER TO agro_app_user;
GRANT CREATE SESSION TO agro_app_user;

COMMIT;